site_name: commandAGI2
theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          paths: [.]
          selection:
            docstring_style: google
          rendering:
            show_source: true
            show_category_heading: true
            show_root_heading: true
            show_object_full_path: true
            heading_level: 2
  - macros:
      module_name: macros
  - awesome-pages
  # - jupyter:
  #     execute: false  # Set to true if you want to execute notebooks during build
  #     include_source: true

# Exclude template files from being processed during build
exclude_docs: |
  /api/template.md
  /examples/template.md

nav:
  - User Guide:
    - 'Introduction': 'index.md'
    - 'Installation': 'installation.md'
    - 'Quick Start': 'quickstart.md'
    - Concepts:
      - 'Overview': 'concepts/index.md'
      - 'Computers': 'concepts/computers.md'
      - 'Provisioners': 'concepts/provisioners.md'
      - 'Daemon': 'concepts/daemon.md'
      - 'Gym Framework': 'concepts/gym.md'
      - 'Types': 'concepts/types.md'
    - Guides:
      - 'Using Provisioners': 'guides/provisioners.md'
      - 'Cloud Containers': 'guides/cloud_containers.md'
    - Tutorials:
      - 'Basic Automation': 'tutorials/basic_automation.md'
  - 'API Reference': 'api/index.md'
  - Examples: 
      - examples/index.md
      - ... # This will automatically include all other .md files in the examples directory
  - For Developers:
    - 'Provisioner System': 'developers/provisioners.md'
    - 'Custom Computers': 'developers/custom_computers.md'

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
