[project]
name = "commandlab"
version = "0.1.0"
description = ""
authors = [{ name = "commandAGI" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["rich", "pydantic", "typer"]


[project.optional-dependencies]
dev = ["pytest", "black", "isort", "ruff"]
local = ["pillow", "pynput", "pyautogui", "mss"]
docker = ["docker"]
kubernetes = ["kubernetes"]
openrl = ["pillow", "numpy", "openrl"]
e2b = ["e2b-desktop"]
scrappybara = ["scrapybara"]
langchain = ["langchain"]

[project.urls]
Homepage = "https://commandagi.com"
Documentation = "https://commandagi.com/developers/commandLAB"
PyPI = "https://pypi.org/project/commandlab/"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
pre-commit = "^4.1.0"

[tool.poetry.group.docker.dependencies]
docker = "^7.1.0"
