[project]
name = "commandLAB"
version = "0.0.1"
description = ""
authors = [{ name = "commandAGI" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.12,<4"
dependencies = [
    "rich==13.9.4",
    "pydantic==2.10.6",
    "typer==0.15.1"
]


[project.optional-dependencies]
# Development dependencies
dev = [
    "pytest==8.3.4",
    "black==25.1.0",
    "isort==6.0.0",
    "ruff==0.9.7",
    "pillow==11.1.0",
]

# Legacy/existing extras for compatibility
local = [
    "pynput==1.7.7",
    "pyautogui==0.9.54",
    "mss==10.0.0"
]
vnc = ["vncdotool==1.2.0"]
docker = ["docker==7.1.0"]
kubernetes = ["kubernetes==32.0.1"]
e2b-desktop = ["e2b-desktop==1.0.2"]
scrapybara = ["scrapybara==2.2.7"]
langchain = ["langchain==0.3.19"]
pig = ["pig-python==0.1.1"]
pytesseract = ["pytesseract==0.3.10"]

# Base daemon client
daemon-client = [
    "requests",
    "pillow",
]

# Cloud provider specific daemon clients
daemon-client-aws = [
    "commandlab[daemon-client]",
    "boto3",
]

daemon-client-azure = [
    "commandlab[daemon-client]",
    "azure-mgmt-containerinstance",
    "azure-identity",
]

daemon-client-gcp = [
    "commandlab[daemon-client]",
    "google-cloud-container",
]

# Docker and Kubernetes daemon clients
daemon-client-docker = [
    "commandlab[daemon-client]",
    "commandlab[docker]",
]

daemon-client-kubernetes = [
    "commandlab[daemon-client]",
    "commandlab[kubernetes]",
]

# All daemon client capabilities
daemon-client-all = [
    "commandlab[daemon-client-aws,daemon-client-azure,daemon-client-gcp,daemon-client-docker,daemon-client-kubernetes]",
]

# Daemon host dependencies
daemon-host = [
    "fastapi",
    "uvicorn",
    "commandlab[local]"
]


[project.urls]
Homepage = "https://commandagi.com"
Documentation = "https://commandagi.com/developers/commandLAB"
PyPI = "https://pypi.org/project/commandLAB/"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
mkdocs-autorefs = "^1.3.1"
mkdocs = "^1.6.1"
mkdocs-material = "^9.6.5"
mkdocstrings = {extras = ["python"], version = "^0.28.1"}
mkdocs-jupyter = "^0.25.1"


[tool.poetry.group.gymnasium.dependencies]
gymnasium = "^1.0.0"
numpy = "^2.2.3"
pillow = "^11.1.0"

